using Spectre.Console;

namespace Smart_Factory_Management_System
{
    internal static class ReportMenuHandler
    {
        public static void Run(Factory factory, Employee loggedInUser)
        {
            AnsiConsole.Clear();
            AnsiConsole.Write(new Rule("[magenta]FACTORY PERFORMANCE & METRIC REPORTS[/]").Centered());

            // Build structural dashboards cleanly using Spectre layouts
            var panel = new Panel(new Markup(
                $"[bold]Generated By:[/] {loggedInUser.Name}\n" +
                $"[bold]Timestamp:[/] {DateTime.Now}\n\n" +
                $"[green]Total Warehouse Items Built:[/] {factory.ProductCount} stocks\n" +
                $"[blue]Active Floor Operations Staff:[/] {factory.EmployeeCount} employees\n" +
                $"[yellow]Total Machinery Assets On-Grid:[/] {factory.MachineCount} machines"
            ))
            {
                Header = new PanelHeader("Factory Diagnostic Snapshot"),
                Padding = new Padding(2, 2, 2, 2),
                Border = BoxBorder.Rounded
            };

            AnsiConsole.Write(panel);

            // You can call your internal encapsulated factory reporter loop here:
            // factory.GenerateSystemReport();

            AnsiConsole.MarkupLine("\n[grey]Press any key to return to the core loop...[/]");
            Console.ReadKey(true);
        }
    }
}
