import os
import re

# 1. Enforce the Output Directory for GitHub Pages
OUTPUT_DIR = 'docs'
os.makedirs(OUTPUT_DIR, exist_ok=True)

html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Factory - Architecture Map</title>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({ startOnLoad: true, theme: 'dark' });
    </script>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #1e1e2e; color: #cdd6f4; margin: 0; padding: 20px; }
        h1, h2 { color: #89b4fa; border-bottom: 1px solid #45475a; padding-bottom: 10px; }
        .container { max-width: 1200px; margin: 0 auto; }
        .mermaid-wrapper { background: #181825; padding: 20px; border-radius: 8px; overflow-x: auto; margin-bottom: 40px; border: 1px solid #313244; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); gap: 20px; }
        .card { background: #11111b; border: 1px solid #313244; border-radius: 8px; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }
        .card-title { color: #f38ba8; font-size: 1.5em; font-weight: bold; margin-bottom: 10px; }
        .file-path { font-size: 0.85em; color: #a6adc8; margin-bottom: 15px; font-style: italic; }
        .section-title { color: #a6e3a1; margin-top: 15px; margin-bottom: 5px; font-weight: bold; }
        ul { list-style-type: none; padding-left: 0; margin: 0; }
        li { background: #181825; margin-bottom: 5px; padding: 8px; border-radius: 4px; font-family: monospace; font-size: 0.9em; border-left: 3px solid #89b4fa; }
        .keyword { color: #cba6f7; }
        .type { color: #f9e2af; }
        .name { color: #89dceb; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🏭 Smart Factory Management System</h1>
        <p>Autogenerated Architecture Map & Repository Documentation</p>
        
        <h2>Interactive UML Class Diagram</h2>
        <div class="mermaid-wrapper">
            <div class="mermaid">
classDiagram
"""

mermaid_code = ""
ui_classes = []
core_classes = []
class_cards_html = ""

# Regex definitions to extract cleanly
class_regex = re.compile(r'class\s+(\w+)(?:\s*:\s*([\w\s,]+))?')
prop_regex = re.compile(r'public\s+([\w\[\]\<\>]+)\s+(\w+)\s*\{\s*get;')
method_regex = re.compile(r'public\s+(?!class)([\w\[\]\<\>]+)\s+(\w+)\s*\(')

for root, _, files in os.walk('.'):
    # Ignore compiled folders and our output directory
    if any(exclude in root for exclude in ['bin', 'obj', '.git', 'docs']):
        continue
        
    for file in files:
        if file.endswith('.cs'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                
                found_classes = class_regex.findall(content)
                if not found_classes: continue
                
                found_props = prop_regex.findall(content)
                found_methods = method_regex.findall(content)
                
                for class_name, inheritance in found_classes:
                    # 2. Categorize for Subgraphs (The "Horizontal Cut" for presentations)
                    if "Handler" in class_name or "UI" in filepath or "Program" in class_name:
                        ui_classes.append(class_name)
                    else:
                        core_classes.append(class_name)
                        
                    # Build HTML Card for the Website
                    card_html = f'''
                    <div class="card">
                        <div class="card-title">{class_name}</div>
                        <div class="file-path">📄 {filepath}</div>
                    '''
                    
                    mermaid_code += f"    class {class_name} {{\n"
                    
                    if found_props:
                        card_html += '<div class="section-title">Properties:</div><ul>'
                        for p_type, p_name in found_props:
                            safe_type_html = p_type.replace('<', '&lt;').replace('>', '&gt;')
                            card_html += f'<li><span class="type">{safe_type_html}</span> <span class="name">{p_name}</span></li>'
                            
                            # 3. Sanitize for Mermaid (Removing [] arrays to prevent Crash!)
                            safe_mermaid_type = p_type.replace('[', '').replace(']', '').replace('<', '~').replace('>', '~')
                            mermaid_code += f"        +{safe_mermaid_type} {p_name}\n"
                        card_html += '</ul>'
                        
                    if found_methods:
                        card_html += '<div class="section-title">Methods:</div><ul>'
                        for m_type, m_name in found_methods:
                            safe_type_html = m_type.replace('<', '&lt;').replace('>', '&gt;')
                            card_html += f'<li><span class="keyword">public</span> <span class="type">{safe_type_html}</span> <span class="name">{m_name}()</span></li>'
                            
                            safe_mermaid_type = m_type.replace('[', '').replace(']', '').replace('<', '~').replace('>', '~')
                            mermaid_code += f"        +{m_name}() {safe_mermaid_type}\n"
                        card_html += '</ul>'
                        
                    mermaid_code += f"    }}\n"
                    card_html += "</div>"
                    class_cards_html += card_html
                    
                    # 4. Generate Relationships
                    if inheritance:
                        parents = [p.strip() for p in inheritance.split(',')]
                        for p in parents:
                            if p and not p.startswith('I'): # Ignore Interfaces for cleaner UML view
                                mermaid_code += f"    {p} <|-- {class_name} : inherits\n"
                                
                    for p_type, p_name in found_props:
                        clean_type = p_type.replace('[]', '')
                        # If type starts with uppercase and isn't basic struct, draw a line
                        if clean_type and clean_type[0].isupper() and clean_type not in ['String', 'Int32', 'Boolean', 'DateTime', 'TimeSpan', 'Int', 'Double']:
                            mermaid_code += f"    {class_name} --> {clean_type} : holds\n"

# Add Subgraphs to Mermaid
mermaid_code += "\n    %% --- Presentation Subgraphs --- \n"
if core_classes:
    mermaid_code += '    subgraph Core_Logic["⚙️ Domain Logic"]\n'
    for c in core_classes:
        mermaid_code += f'        {c}\n'
    mermaid_code += '    end\n\n'
    
if ui_classes:
    mermaid_code += '    subgraph UI_Handlers["🖥️ User Interface"]\n'
    for c in ui_classes:
        mermaid_code += f'        {c}\n'
    mermaid_code += '    end\n'

# Stitch the HTML together
final_html = html_content + mermaid_code + """
            </div>
        </div>
        
        <h2>Detailed Class Map</h2>
        <div class="grid">
""" + class_cards_html + """
        </div>
    </div>
</body>
</html>
"""

# 5. Write the output file exactly where GitHub Pages looks for it
output_path = os.path.join(OUTPUT_DIR, 'index.html')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(final_html)

print(f"✅ Documentation successfully generated at: {output_path}")
