using System.Text;
using Spectre.Console;

namespace Smart_Factory_Management_System;

internal static class AccountingMenuHandler
{
    public static void Run(Factory factory, Employee loggedInUser, ILoggerService loggerService,
        IFileSystemService fileSystem, IJsonRepository<ReportRequest> reportRequestsRepo)
    {
        if (loggedInUser is not Accountant)
        {
            AnsiConsole.MarkupLine(string.Format(Common.AccessDeniedSection, loggedInUser.Role, "Accounting"));
            AnsiConsole.WriteLine(Common.PressKeyToReturn);
            Console.ReadKey(true);
            return;
        }

        while (true)
        {
            AnsiConsole.Clear();
            AnsiConsole.Write(new Rule($"[magenta]{Accounting.Title}[/]").Centered());

            var menuOptions = MenuOptions.AccountingMenu.Select((item, index) => $"{index + 1}. {item}").ToList();
            var choice = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title(Common.ChooseAction)
                    .AddChoices(menuOptions));

            var option = choice.Split(". ", 2)[1];
            switch (option)
            {
                case "View Batches":
                    ShowBatches(factory);
                    loggerService.LogInfo(LogOrigin.User, LogEvent.BatchesViewed, loggedInUser.Username);
                    break;
                case "Process Report Requests":
                    ProcessReportRequests(factory, loggedInUser, loggerService, fileSystem, reportRequestsRepo);
                    break;
                case "Return to Main Menu":
                    return;
            }

            AnsiConsole.MarkupLine(Common.PressKeyToContinue);
            Console.ReadKey(true);
        }
    }

    private static void ShowBatches(Factory factory)
    {
        AnsiConsole.WriteLine();
        if (factory.BatchCount == 0)
        {
            AnsiConsole.MarkupLine(Accounting.NoBatches);
            return;
        }

        var table = new Table().AddColumn("BatchId").AddColumn("Product").AddColumn("Qty").AddColumn("UnitCost")
            .AddColumn("UnitSell").AddColumn("Sold");
        for (var i = 0; i < factory.BatchCount; i++)
        {
            var b = factory.Batches[i];
            table.AddRow(b.BatchId, b.ProductName, b.Quantity.ToString(), b.UnitProductionCost.ToString("F2"),
                b.UnitSellPrice?.ToString("F2") ?? "-", b.IsSold ? "Yes" : "No");
        }

        AnsiConsole.Write(table);
    }


    private static void ProcessReportRequests(Factory factory, Employee accountant, ILoggerService loggerService,
        IFileSystemService fileSystem, IJsonRepository<ReportRequest> reportRequestsRepo)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule($"[magenta]{Accounting.ProcessReportRequestsTitle}[/]").Centered());

        var pendingRequests = factory.PendingReportRequests.Take(factory.ReportRequestCount)
            .Where(r => r.Status == ReportStatus.Pending).ToList();

        if (!pendingRequests.Any())
        {
            AnsiConsole.MarkupLine(Accounting.NoPendingRequests);
            return;
        }

        var selector = new SelectionPrompt<ReportRequest>()
            .Title(Accounting.SelectRequestToFulfill)
            .AddChoices(pendingRequests);

        var chosen = AnsiConsole.Prompt(selector);

        chosen.Fulfill();
        reportRequestsRepo.Save(factory.PendingReportRequests);

        ExportReportToCsv(chosen, factory, fileSystem);

        AnsiConsole.MarkupLine(
            string.Format(Accounting.RequestFulfilled, chosen.ReportType, chosen.RequestId, accountant.Name));
        loggerService.LogInfo(LogOrigin.User, LogEvent.ReportRequestsProcessed,
            $"Report '{chosen.ReportType}' (Req ID: {chosen.RequestId}) fulfilled by {accountant.Username}");
    }

    private static void ExportReportToCsv(ReportRequest request, Factory factory, IFileSystemService fileSystem)
    {
        string directoryPath;
        if (request.ExportDestination == "Desktop")
            directoryPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
        else
            directoryPath = Path.Combine(fileSystem.BaseDirectory, "Reports");

        if (!Directory.Exists(directoryPath)) Directory.CreateDirectory(directoryPath);

        var fileName =
            $"{request.ReportType.Replace(" ", "_")}_{request.RequestId}_{DateTime.Now:yyyyMMdd_HHmmss}.csv";
        var fullPath = Path.Combine(directoryPath, fileName);

        var csvBuilder = new StringBuilder();

        if (request.ReportType == "Production Summary")
        {
            var inventoryValue = factory.Inventory.Where(p => !p.IsSold).Sum(p => p.SellingPrice * p.Quantity);
            var totalUnits = factory.Inventory.Where(p => !p.IsSold).Sum(p => p.Quantity);
            csvBuilder.AppendLine("Metric,Value");
            csvBuilder.AppendLine($"Generated By,{request.RequestedByDirectorName}");
            csvBuilder.AppendLine($"Timestamp,{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            csvBuilder.AppendLine($"Inventory Item Types,{factory.Inventory.Count(p => !p.IsSold)}");
            csvBuilder.AppendLine($"Inventory Units,{totalUnits}");
            csvBuilder.AppendLine($"Est Inventory Value,${inventoryValue:F2}");
            csvBuilder.AppendLine($"Employees,{factory.Employees.Count}");
            csvBuilder.AppendLine($"Machines,{factory.Machines.Count}");

            // Batches Section
            csvBuilder.AppendLine();
            csvBuilder.AppendLine("Production Batches");
            csvBuilder.AppendLine("BatchId,Product,Qty,Production Cost/Unit,Sell Price/Unit,Status");

            double totalExpenses = 0;
            double totalIncome = 0;
            foreach (var batch in factory.Batches)
            {
                totalExpenses += batch.TotalCost;
                if (batch.IsSold && batch.UnitSellPrice.HasValue)
                    totalIncome += batch.UnitSellPrice.Value * batch.Quantity;

                var status = batch.IsSold ? "Sold" : "Produced";
                var sellPrice = batch.IsSold ? $"{batch.UnitSellPrice ?? 0.0:F2}" : "0.00";
                csvBuilder.AppendLine(
                    $"{batch.BatchId},{batch.ProductName},{batch.Quantity},{batch.UnitProductionCost:F2},{sellPrice},{status}");
            }

            // Financial Summary Section
            var totalProfit = totalIncome - totalExpenses;
            csvBuilder.AppendLine();
            csvBuilder.AppendLine("Financial Summary");
            csvBuilder.AppendLine($"Total Expenses (Production Cost),${totalExpenses:F2}");
            csvBuilder.AppendLine($"Total Income (Sales Revenue),${totalIncome:F2}");
            csvBuilder.AppendLine($"Total Net Profit/Loss,${totalProfit:F2}");
        }
        else if (request.ReportType == "Employee Report")
        {
            csvBuilder.AppendLine("Id,Name,Username,Role,Activity");
            foreach (var emp in factory.Employees)
            {
                var activity = emp.ShowActivity().Replace(",", ";");
                csvBuilder.AppendLine($"{emp.Id},{emp.Name},{emp.Username},{emp.Role},{activity}");
            }
        }
        else if (request.ReportType == "Order Backlog Summary")
        {
            csvBuilder.AppendLine("OrderId,Product,Qty,Completed,AssignedTechId,Status");
            foreach (var order in factory.PendingOrders)
            {
                var status = order.IsComplete ? "Complete" : "In Progress";
                csvBuilder.AppendLine(
                    $"{order.OrderId},{order.ProductName},{order.Quantity},{order.CompletedCount},{order.AssignedTechnicianId},{status}");
            }
        }

        File.WriteAllText(fullPath, csvBuilder.ToString());
        AnsiConsole.MarkupLine($"[green]✔ Success: Report exported to CSV at: [underline]{fullPath}[/][/]");
    }

    public static void RunQuickActions(Factory factory, Employee loggedInUser, ILoggerService loggerService,
        IFileSystemService fileSystem, IJsonRepository<ReportRequest> reportRequestsRepo)
    {
        while (true)
        {
            AnsiConsole.Clear();
            AnsiConsole.Write(new Rule($"[magenta]{Accounting.QuickActionsTitle}[/]").Centered());

            var menuChoices = new List<string>
            {
                Accounting.QuickActionViewBatches,
                Accounting.QuickActionViewProductionSummary,
                Accounting.QuickActionProcessReportRequests,
                Accounting.QuickActionReturnToMainMenu
            };

            var choice = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title(Common.ChooseAction)
                    .AddChoices(menuChoices));

            var option = choice.Split(". ", 2)[1];
            switch (option)
            {
                case "View Batches":
                    ShowBatches(factory);
                    loggerService.LogInfo(LogOrigin.User, LogEvent.BatchesViewed, loggedInUser.Username);
                    break;
                case "Process Report Requests":
                    ProcessReportRequests(factory, loggedInUser, loggerService, fileSystem, reportRequestsRepo);
                    break;
                case "View Production Summary":
                    ReportMenuHandler.ShowProductionSummary(factory, loggedInUser);
                    loggerService.LogInfo(LogOrigin.User, LogEvent.ProductionSummaryReportGenerated,
                        loggedInUser.Username);
                    break;
                case "Return to Main Menu":
                    return;
            }

            AnsiConsole.MarkupLine(Common.PressKeyToContinue);
            Console.ReadKey(true);
        }
    }
}