using Spectre.Console;

namespace Smart_Factory_Management_System;

internal static class ReportMenuHandler
{
    public static void Run(Factory factory, Employee loggedInUser, ILoggerService loggerService)
    {
        while (true)
        {
            AnsiConsole.Clear();
            AnsiConsole.Write(new Rule("[magenta]FACTORY PERFORMANCE & METRIC REPORTS[/]").Centered());

            var choices = MenuOptions.ReportMenu.Select((item, index) => $"{index + 1}. {item}").ToList();
            if (loggedInUser is Director)
                choices.Insert(choices.Count - 1, $"{choices.Count}. Request Printable Report");

            var choice = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title("Choose a report:")
                    .AddChoices(choices));

            var option = choice.Split(". ", 2)[1];
            switch (option)
            {
                case "Production Summary":
                    ShowProductionSummary(factory, loggedInUser);
                    break;
                case "Employee Report":
                    ShowEmployeeReport(factory);
                    break;
                case "Batch Revenue Summary":
                    ShowBatchRevenueSummary(factory);
                    break;
                case "Order Backlog Summary":
                    ShowOrderBacklogSummary(factory);
                    break;
                case "Request Printable Report":
                    RequestPrintableReport(factory, loggedInUser);
                    break;
                case "Return to Main Menu":
                    return;
            }
        }
    }

    private static void ShowEmployeeReport(Factory factory)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule("[magenta]Employee Report[/]").Centered());
        EmployeeMenuHandler.DisplayStaffTable(factory);
        Pause();
    }

    private static void RequestPrintableReport(Factory factory, Employee director)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule("[magenta]Request Printable Report[/]").Centered());

        var reportType = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title("Select report type to request:")
                .AddChoices("Production Summary", "Employee Report", "Batch Revenue Summary", "Order Backlog Summary"));

        factory.AddReportRequest(new ReportRequest(reportType, director.Name));

        AnsiConsole.MarkupLine($"[green]✔ Request for '{reportType}' submitted successfully![/]");
        Pause();
    }

    private static void ShowProductionSummary(Factory factory, Employee loggedInUser)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule("[magenta]Production Summary[/]").Centered());

        double inventoryValue = 0;
        foreach (var product in factory.Inventory)
        {
            inventoryValue += product.SellingPrice * product.Quantity;
        }

        var grid = new Grid().AddColumns(2);
        grid.AddRow("[bold white]Generated By[/]", Markup.Escape(loggedInUser.Name));
        grid.AddRow("[bold white]Timestamp[/]", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        grid.AddRow("[bold white]Inventory Item Types[/]", factory.Inventory.Count.ToString());
        grid.AddRow("[bold white]Inventory Units[/]", GetTotalInventoryUnits(factory).ToString());
        grid.AddRow("[bold white]Estimated Inventory Value[/]", $"${inventoryValue:F2}");
        grid.AddRow("[bold white]Employees[/]", factory.Employees.Count.ToString());
        grid.AddRow("[bold white]Machines[/]", factory.Machines.Count.ToString());

        AnsiConsole.Write(new Panel(grid).Header("[bold]Factory Diagnostic Snapshot[/]").Border(BoxBorder.Rounded));
        Pause();
    }

    private static void ShowBatchRevenueSummary(Factory factory)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule("[magenta]Batch Revenue Summary[/]").Centered());

        if (factory.BatchCount == 0)
        {
            AnsiConsole.MarkupLine("[yellow]No batches have been recorded yet.[/]");
            Pause();
            return;
        }

        var table = new Table().Border(TableBorder.Rounded);
        table.AddColumn("BatchId");
        table.AddColumn("Product");
        table.AddColumn("Qty");
        table.AddColumn("Cost");
        table.AddColumn("Sell Price");
        table.AddColumn("Status");

        double totalPotentialRevenue = 0;
        double totalCost = 0;

        for (var i = 0; i < factory.BatchCount; i++)
        {
            var batch = factory.Batches[i];

            totalCost += batch.TotalCost;
            if (batch.UnitSellPrice.HasValue) totalPotentialRevenue += batch.UnitSellPrice.Value * batch.Quantity;

            table.AddRow(
                batch.BatchId,
                batch.ProductName,
                batch.Quantity.ToString(),
                $"${batch.UnitProductionCost:F2}",
                batch.UnitSellPrice?.ToString("F2") ?? "-",
                batch.IsSold ? "Sold" : batch.IsPriced ? "Priced" : "Open"
            );
        }

        AnsiConsole.Write(table);
        AnsiConsole.Write(new Panel(new Markup(
            $"[bold white]Total Production Cost:[/] ${totalCost:F2}\n" +
            $"[bold white]Potential Revenue:[/] ${totalPotentialRevenue:F2}")
        ).Border(BoxBorder.Rounded).Header("[bold]Batch Summary[/]"));
        Pause();
    }

    private static void ShowOrderBacklogSummary(Factory factory)
    {
        AnsiConsole.Clear();
        AnsiConsole.Write(new Rule("[magenta]Order Backlog Summary[/]").Centered());

        if (factory.OrderCount == 0)
        {
            AnsiConsole.MarkupLine("[yellow]No production orders are currently pending.[/]");
            Pause();
            return;
        }

        var table = new Table().Border(TableBorder.Rounded);
        table.AddColumn("OrderId");
        table.AddColumn("Product");
        table.AddColumn("Qty");
        table.AddColumn("Completed");
        table.AddColumn("Assigned Tech");
        table.AddColumn("Status");

        foreach (var order in factory.PendingOrders)
        {
            table.AddRow(
                order.OrderId,
                order.ProductName,
                order.Quantity.ToString(),
                order.CompletedCount.ToString(),
                order.AssignedTechnicianId.ToString(),
                order.IsComplete ? "Complete" : "In Progress"
            );
        }

        AnsiConsole.Write(table);
        Pause();
    }

    private static int GetTotalInventoryUnits(Factory factory)
    {
        var totalUnits = 0;

        foreach (var product in factory.Inventory)
        {
            totalUnits += product.Quantity;
        }

        return totalUnits;
    }

    private static void Pause()
    {
        AnsiConsole.MarkupLine("\n[grey]Press any key to return...[/]");
        Console.ReadKey(true);
    }
}