<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>SmartFactory_ManagementSystem</AssemblyName>
        <Authors>CasperGamingOne;Ganea Andreea</Authors>
        <TargetFramework>net10.0</TargetFramework>
        <Version>0.16</Version>
        <RootNamespace>Smart_Factory_Management_System</RootNamespace>
        <Description>A professional-grade smart factory simulation system, simulated ofc.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.57.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj"/>
        <ProjectReference Include="..\Services\Services.csproj"/>
        <ProjectReference Include="..\Text\Text.csproj"/>
    </ItemGroup>

</Project>
