namespace Smart_Factory_Management_System;

public static class Reports
{
    public const string Title = "FACTORY PERFORMANCE & METRIC REPORTS";
    public const string SelectReport = "Choose a report:";
    public const string RequestPrintableReport = "Request Printable Report";
    public const string SelectReportToRequest = "Select report type to request:";
    public const string RequestSubmitted = "[green]✔ Request for '{0}' submitted successfully![/]";
    public const string GeneratedBy = "[bold white]Generated By[/]";
    public const string Timestamp = "[bold white]Timestamp[/]";
    public const string InventoryItemTypes = "[bold white]Inventory Item Types[/]";
    public const string InventoryUnits = "[bold white]Inventory Units[/]";
    public const string EstInventoryValue = "[bold white]Estimated Inventory Value[/]";
    public const string Employees = "[bold white]Employees[/]";
    public const string Machines = "[bold white]Machines[/]";
    public const string SnapshotPanelHeader = "Factory Diagnostic Snapshot";

    public const string NoBatches = "[yellow]No batches have been recorded yet.[/]";
    public const string TotalProductionCost = "[bold white]Total Production Cost:[/]";
    public const string PotentialRevenue = "[bold white]Potential Revenue:[/]";
    public const string BatchSummaryPanelHeader = "Batch Summary";

    public const string NoPendingOrders = "[yellow]No production orders are currently pending.[/]";

    public const string OverviewTitle = "FACTORY REPORT MENU";
    public const string ChooseFactoryReport = "Choose a factory report:";
    public const string FactoryOverviewTitle = "Factory Overview";
    public const string StaffingReportTitle = "Staffing Report";
    public const string MachineFleetReportTitle = "Machine Fleet Report";
    public const string InventoryReportTitle = "Inventory Report";

    public const string RequestedBy = "[bold white]Requested By[/]";
    public const string PendingOrders = "[bold white]Pending Orders[/]";
    public const string Batches = "[bold white]Batches[/]";
    public const string FactorySnapshotHeader = "Factory Snapshot";
    public const string NoStaff = "[yellow]No staff registered.[/]";
    public const string NoMachines = "[yellow]No machines registered.[/]";
    public const string NoInventory = "[yellow]No inventory items registered.[/]";
    public const string TotalUnits = "[bold white]Total Units:[/]";
    public const string EstInventoryValueTotal = "[bold white]Estimated Inventory Value:[/]";
    public const string InventoryTotalsHeader = "Inventory Totals";

    public const string ReportFulfilledHeader = "Printable Report Fulfilled";
    public const string ReportFulfilledNotification = "Your requested report '{0}' (Req ID: [cyan]#{1}[/]) is ready!";
    public const string ReportFulfilledAcknowledge = "[grey]Press any key to acknowledge...[/]";

    public const string ChooseExportFolderPrompt = "Choose target export folder for the report:";
    public const string ExportDestDesktop = "Desktop";
    public const string ExportDestReportsFolder = "Program Reports Folder";
    public const string ExportDestSelected = "Export destination selected: [cyan]{0}[/]";

    public const string ProductionSummaryHeader = "Production Summary & Financials";
    public const string BatchesDetailsHeader = "[bold cyan] Factory Production Batches Details [/]";
    public const string ColumnBatchId = "BatchId";
    public const string ColumnProduct = "Product";
    public const string ColumnQty = "Qty";
    public const string ColumnProductionCostUnit = "Production Cost/Unit";
    public const string ColumnSellPriceUnit = "Sell Price/Unit";
    public const string ColumnStatus = "Status";
    public const string StatusSold = "[green]Sold[/]";
    public const string StatusProduced = "[grey]Produced[/]";
    public const string NoBatchesProduced = "[grey]No batches produced yet.[/]";

    public const string FinanceExpensesLabel = "[bold white]Total Expenses (Production Cost):[/]";
    public const string FinanceIncomeLabel = "[bold white]Total Income (Sales Revenue):[/]";
    public const string FinanceProfitLabel = "[bold white]Total Net Profit/Loss:[/]";
    public const string FinanceHeader = " Factory Financial Summary ";

    public const string OrderBacklogSummaryHeader = "Order Backlog Summary";
    public const string ColumnOrderId = "OrderId";
    public const string ColumnCompleted = "Completed";
    public const string ColumnAssignedTech = "Assigned Tech";
    public const string StatusComplete = "Complete";
    public const string StatusInProgress = "In Progress";
}